services:
  identifier:
    security_opt:
      - label=disable
    ports:
      - "1080:80"
    environment:
      LOG_ALLOWED_GROUPS: true
      LOG_SESSION: true
      
  dispatcher:
    security_opt:
      - label=disable
  resource:
    security_opt:
      - label=disable
  migrations:
    security_opt:
      - label=disable
  delta-notifier:
    security_opt:
      - label=disable
  security:
    security_opt:
      - label=disable
  triplestore:
    security_opt:
      - label=disable
    ports:
      - "8890:8890"

  login:
    security_opt:
      - label=disable
  registration:
    security_opt:
      - label=disable
    ports:
      - "1081:80"
