x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.1.1
    volumes:
      - ./config/dispatcher:/config:ro,z
    labels:
      - "logging=true"
    logging: *default-logging

  # Your extra services here
  resource:
    image: semtech/mu-cl-resources:1.27.2
    volumes:
      - ./config/resources:/config:ro,z
    labels:
      - "logging=true"
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations:ro,z
    labels:
      - "logging=true"
    logging: *default-logging
    networks:
        triplestore:

  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/:ro,z
    labels:
      - "logging=true"
    logging: *default-logging

  security:
    image: semtech/sparql-parser:0.0.15
    volumes:
      - ./config/authorization/:/config/:ro,z
      - ./data/authorization:/data/:rw,Z
    labels:
      - "logging=true"
    logging: *default-logging
    networks:
        triplestore:
        default:
            aliases:
                - database

  triplestore:
    image: redpencil/virtuoso:1.3.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini:ro,z
      - triplestore_data:/data/:Z
    labels:
      - "logging=true"
    logging: *default-logging
    networks:
        triplestore:
            aliases:
                - database

networks:
    default: {}
    triplestore: {}

volumes:
    triplestore_data: {}
